name: Build OGX-BT-Hybrid

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PICO_SDK_VERSION: "2.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3

      - name: Get Pico SDK
        run: git clone --branch ${{ env.PICO_SDK_VERSION }} --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Get btstack + dependencies
        run: |
          git clone --branch v1.6.2 --depth 1 https://github.com/bluekitchen/btstack.git external/bluepad32/external/btstack
          cd external/bluepad32/external/btstack
          patch -p1 < $GITHUB_WORKSPACE/external/patches/btstack_l2cap.diff || true
          cd $GITHUB_WORKSPACE
          printf '#ifndef _SDK_CONFIG_H_\n#define _SDK_CONFIG_H_\n#define CONFIG_BLUEPAD32_MAX_DEVICES 1\n#define CONFIG_BLUEPAD32_MAX_ALLOWLIST 4\n#define CONFIG_BLUEPAD32_GAP_SECURITY 1\n#define CONFIG_BLUEPAD32_ENABLE_BLE_BY_DEFAULT 1\n#define CONFIG_BLUEPAD32_PLATFORM_CUSTOM\n#define CONFIG_TARGET_PICO_W\n#define CONFIG_BLUEPAD32_LOG_LEVEL 0\n#endif\n' > external/bluepad32/src/components/bluepad32/include/sdkconfig.h
          git clone https://github.com/PetteriAimonen/libfixmath.git external/libfixmath
          git clone https://github.com/wiredopposite/Pico-PIO-USB.git external/Pico-PIO-USB

      - name: Build
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
        run: |
          mkdir -p build
          cd build
          cmake -DPICO_SDK_PATH=${PICO_SDK_PATH} -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j$(nproc)
          find . -maxdepth 1 -name "*.uf2"

      - name: Upload UF2
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OGX-BT-Hybrid-PICO2W
          path: build/*.uf2
          if-no-files-found: error
